/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class SegmentIterator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SegmentIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SegmentIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pocketsphinxJNI.delete_SegmentIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SegmentIterator(Decoder d) {
    this(pocketsphinxJNI.new_SegmentIterator(Decoder.getCPtr(d), d), true);
  }

  public String getWord() {
    return pocketsphinxJNI.SegmentIterator_getWord(swigCPtr, this);
  }

  public SegmentIterator getNext() {
    long cPtr = pocketsphinxJNI.SegmentIterator_getNext(swigCPtr, this);
    return (cPtr == 0) ? null : new SegmentIterator(cPtr, false);
  }

}
