/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class SWIGTYPE_p__self {
  private long swigCPtr;

  protected SWIGTYPE_p__self(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p__self() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p__self obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

